set(SRC_FILES
    App.cpp
    LevelManager.cpp
    Plant.cpp
    PeashooterPlant.cpp
    SunflowerPlant.cpp
    RepeaterPlant.cpp
    PotatoMinePlant.cpp
    WallnutPlant.cpp
    CherryBombPlant.cpp
    SnowPeaPlant.cpp
    ChomperPlant.cpp
    Zombie.cpp
    BasicZombie.cpp
    ConeZombie.cpp
    BucketZombie.cpp
    PoleVaulterZombie.cpp
    FlagZombie.cpp
    LawnMower.cpp
    Button.cpp
    PlantCard.cpp
    PlantRegistry.cpp
    GameStateManager.cpp
    LevelConfigParser.cpp
)

set(INCLUDE_FILES
    App.hpp
    Background.hpp
    LevelManager.hpp
    Plant.hpp
    PeashooterPlant.hpp
    SunflowerPlant.hpp
    RepeaterPlant.hpp
    PotatoMinePlant.hpp
    WallnutPlant.hpp
    CherryBombPlant.hpp
    SnowPeaPlant.hpp
    ChomperPlant.hpp
    Zombie.hpp
    BasicZombie.hpp
    ConeZombie.hpp
    BucketZombie.hpp
    PoleVaulterZombie.hpp
    FlagZombie.hpp
    LawnMower.hpp
    Button.hpp
    PlantCard.hpp
    PlantRegistry.hpp
    GameStateManager.hpp
    LevelConfig.hpp
    LevelConfigParser.hpp
)

set(TEST_FILES
)
